import pandas as pd

# import the csv file using pandas

data = pd.read_csv('https://data.cms.gov/sites/default/files/2023-04/67157de9-d962-4af0-bf0e-3578b3afec58/inpatient.csv' ,
                   sep='|')
# quick check of the data

data

# list the columns to identify codexes

for i in data.columns:
     print(i)

# find and print all codexes that start with "ICD"
# print the list
# count the number of columns generated by the list

icd_codes = [i for i in data if i.startswith('ICD')]
print("ICD Codes:\n" ,data[icd_codes])
print("The number of ICD codes is:\n" ,data.columns.str.startswith('ICD_').sum())

claim_codes = [j for j in data if j.startswith('CLM')]
print("CLM Codes:\n" ,data[claim_codes])
print("The number of claim codes is:\n" ,data.columns.str.startswith('CLM_').sum())

